"use client";
import {useState} from "react";
import {motion} from "motion/react";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";

export function AuthForm({mode}:{mode:"login"|"register"}){
  const router=useRouter();const params=useSearchParams();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const payload=Object.fromEntries(form);const response=await fetch(`/backend/api/v1/auth/${mode}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok){setError(body.message||"We could not complete that request.");setBusy(false);return}router.push(params.get("next")|| (body.data.role==="admin"?"/admin":"/account"));router.refresh()}
  return <div className="bg-[#f6f4ef] px-5 py-16"><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className="mx-auto max-w-md rounded-[2rem] bg-white p-8 shadow-xl shadow-slate-900/5"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-700">Shield secure access</p><h1 className="mt-3 text-3xl font-semibold">{mode==="login"?"Welcome back":"Create your account"}</h1><p className="mt-2 text-slate-600">{mode==="login"?"Manage orders, care and pharmacy operations.":"Save favourites and keep your orders together."}</p><form onSubmit={submit} className="mt-8 space-y-4">{mode==="register"&&<><Field name="name" label="Full name"/><Field name="phone" label="Phone number"/></>}<Field name="email" label="Email address" type="email"/><Field name="password" label="Password" type="password"/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-full bg-emerald-700 px-5 py-3.5 font-semibold text-white disabled:opacity-60">{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button></form><p className="mt-6 text-center text-sm text-slate-600">{mode==="login"?"New to Shield? ":"Already registered? "}<Link className="font-semibold text-emerald-700" href={mode==="login"?"/register":"/login"}>{mode==="login"?"Create an account":"Sign in"}</Link></p></motion.div></div>
}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label className="block text-sm font-semibold">{label}<input required name={name} type={type} minLength={type==="password"?8:undefined} className="mt-2 w-full rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-emerald-600"/></label>}
